Feature/intake3.0
FRC701/astrid-2020 pull request #10
Opened 2020-01-25 22:15 UTC by NWSchallock

PTAL

2020-01-26 22:12 UTC, duane701 commented
7e34805 should be squashed into the previous commit.

2020-01-26 22:13 UTC, duane701 requested changes

2020-01-26 22:13 UTC, duane701 commented on src/main/include/commands/IntakeOn.h
> +  IntakeOn(double speed, Intake& intake);
Subsystems goes first.

```suggestion
  IntakeOn(Intake& intake, double speed);
```

2020-01-26 22:13 UTC, duane701 commented on src/main/cpp/commands/IntakeOn.cpp
> +IntakeOn::IntakeOn(double speed, Intake& intake)
Subsystem goes first. And you'll have to change the initializer list order.

```suggestion
IntakeOn::IntakeOn(Intake& intake, double speed)
```

2020-01-26 22:13 UTC, duane701 commented on src/main/cpp/RobotContainer.cpp
> +  frc::SmartDashboard::PutData("Intake 100 percent", new IntakeOn(1.0, mIntake));
Really? Could we buy a preference? They're pretty cheap.

No change required.

2020-01-26 22:14 UTC, duane701 commented
FTP

2020-01-26 22:58 UTC, toxicoreos commented
PTAL

2020-01-26 23:37 UTC, duane701 requested changes
FTP

2020-01-26 23:37 UTC, duane701 commented on src/main/include/commands/IntakeOn.h
> +#include <subsystems/Intake.h>
Our subsystem includes use `"`

```suggestion
#include "subsystems/Intake.h"
```

2020-02-01 02:06 UTC, duane701 commented
Replaced by #24

2020-02-01 02:06 UTC, closed without merging