Feature/shooter.v2
FRC701/astrid-2020 pull request #15
Opened 2020-01-26 18:18 UTC by KenyonSchep

Basic subsystem with shoot command, falcons, pistons, and driver station buttons
PTAL

2020-01-26 23:18 UTC, duane701 requested changes

2020-01-26 23:18 UTC, duane701 commented on src/main/include/subsystems/Shooter.h
> +#include "frc/WPILib.h"
Remove WPILib.h. Add specific includes. There might not be a lot to add.

2020-01-26 23:18 UTC, duane701 commented on src/main/include/subsystems/Shooter.h
> +#include "ctre/Phoenix.h"
Remove Phoenix.h. Add specific includes. There might not be a lot to add.

2020-01-26 23:18 UTC, duane701 commented on src/main/cpp/commands/Shoot.cpp
> +: mshooter1(mshooter1)
Seems like this is fixed later on. `cause this doesn't work.

2020-01-26 23:18 UTC, duane701 commented on src/main/cpp/subsystems/Shooter.cpp
> +: mshooterleft{shooterleft}
This is better.

2020-01-26 23:18 UTC, duane701 commented on src/main/cpp/subsystems/Shooter.cpp
>    constexpr double TPR {2048};
Constants are start with `k`. What is TPR? Let's limit abbreviations. Please write out what LTR is.

2020-01-26 23:18 UTC, duane701 commented on src/main/include/commands/HoodOutFull.h
> +  Shooter* mShooter;
Use a reference for subsystems

```suggestion
  Shooter& mShooter;
```

2020-01-26 23:18 UTC, duane701 commented on src/main/include/commands/HoodOutFull.h
> +  HoodOutFull();
Need to construct commands with subsystems

```suggestion
  HoodOutFull(Shooter& shooter);
```

2020-01-26 23:18 UTC, duane701 commented on src/main/cpp/commands/HoodOutFull.cpp
> +HoodOutFull::HoodOutFull() {
Construct with a subsystem

```suggestion
HoodOutFull::HoodOutFull(Shooter& shooter)
: mShooter(shooter)
 {
```

2020-01-26 23:18 UTC, duane701 commented on src/main/cpp/commands/HoodRetract.cpp
> +HoodRetract::HoodRetract() {
Same comments as HoodOutFull.

2020-01-26 23:18 UTC, duane701 commented on src/main/include/commands/HoodRetract.h
> +  HoodRetract();
Same comments as `HoodOutFull`.

2020-01-26 23:18 UTC, duane701 commented on src/main/cpp/commands/LatchDisengage.cpp
> +LatchDisengage::LatchDisengage() {
See previous comments about subsystems and commands. Commands need subsystems by reference

```suggestion
LatchDisengage::LatchDisengage(Shooter& shooter) {
```

2020-01-26 23:18 UTC, duane701 commented on src/main/cpp/subsystems/Shooter.cpp
> +constexpr frc::DoubleSolenoid::Value kLatchDisengage {frc::DoubleSolenoid::kReverse};
Put the `constexpr`'s all together into a `namespace {` block.

2020-01-26 23:18 UTC, duane701 commented on src/main/include/commands/LatchDisengage.h
> +  LatchDisengage();
More subsystems

2020-01-26 23:18 UTC, duane701 commented on src/main/include/commands/LatchEngage.h
> +  Shooter* mShooter;
Subsystem by reference

```suggestion
  Shooter& mShooter;
```

2020-01-26 23:18 UTC, duane701 commented on src/main/cpp/subsystems/Shooter.cpp
> +  mshooterleft.Config_kF(0, f, 10);
Prefix constants with a `k`. E.g `kP`, `kI`, etc.

2020-01-26 23:18 UTC, duane701 commented on src/main/include/subsystems/Shooter.h
> +  double p, i, d, f;
pidf are all constants. Put these in the .cpp at the top in the `namespace {` block.

2020-01-26 23:18 UTC, duane701 commented on src/main/cpp/subsystems/Shooter.cpp
> +, p(0), i(0), d(0), f(0)
This goes away when these are `constexpr`

2020-01-28 02:51 UTC, duane701 commented
LGTM -- Rebase

2020-01-30 00:45 UTC, closed without merging

2020-01-30 00:50 UTC, KenyonSchep commented
Replaced by #30