Feature/conveyor2.0
FRC701/astrid-2020 pull request #8
Opened 2020-01-25 22:11 UTC by toxicoreos

PTAL

2020-01-26 17:24 UTC, duane701 requested changes

2020-01-26 17:24 UTC, duane701 commented on src/main/include/subsystems/Conveyor.h
> +  int CurrentBallCount();
Let's rename to `BallCount`. The count is always current.

```suggestion
  int BallCount();
```

2020-01-26 17:24 UTC, duane701 commented on src/main/cpp/subsystems/Conveyor.cpp
> +void Conveyor::SetConveyor()
`SetConveyor` looks like a command. Should this logic be in a command?

2020-01-26 17:24 UTC, duane701 commented on src/main/include/commands/SetConveyor.h
> + */
This comment can be removed, next time this file is edited.

2020-01-26 17:24 UTC, duane701 commented on src/main/cpp/commands/SetConveyor.cpp
> +  mConveyor.SetConveyor();
The code in `Conveyor::SetConveyor` should be here. `Conveyor::SetConveyor` should be much more simple.

2020-01-26 17:24 UTC, duane701 commented on src/main/cpp/RobotContainer.cpp
> +  frc2::Trigger( [this] { return mConveyor.IsBallExiting(); }).WhenInactive( [this] { mConveyor.BallIntakeExiting(); });
I think we need the complements of these buttons as well. That is we need both Active and Inactive states from both sensors.

A logic diagram for ball counting should be designed. Some test code would be useful.

2020-01-26 18:03 UTC, duane701 commented on src/main/cpp/subsystems/Conveyor.cpp
> +void Conveyor::SetConveyor()
I'm open to an argument that we need to leave this in place until we design a complete ball counter. But ... you need to convince me.

2020-01-26 19:59 UTC, duane701 commented on src/main/cpp/subsystems/Conveyor.cpp
> +    if((IsBallComing() && BallCount() < 5) /* TODO: add in here: || (BallCount() > 0 && IsShooting()) */ )
Add an `IsShooting()` method to Conveyor that returns `false`.  With the todo in that function to calling the shooter.

2020-01-26 22:26 UTC, NWSchallock commented
PTAL @duane701

2020-01-26 23:35 UTC, duane701 requested changes
FTP

2020-01-26 23:35 UTC, duane701 commented on src/main/include/RobotContainer.h
> +#include <subsystems/Conveyor.h>
Our subsystems use `"`

```suggestion
#include "subsystems/Conveyor.h"
```

2020-01-28 04:51 UTC, duane701 commented
LGTM -- Rebase after Jason

Or you can race, first one wins, last on rebases again, and again, and again.

2020-02-01 01:57 UTC, NWSchallock commented
Replaced by #33

2020-02-01 01:57 UTC, closed without merging