Feature/doo hickey.v2
FRC701/astrid-2020 pull request #9
Opened 2020-01-25 22:13 UTC by jasonplatte

PTAL

2020-01-26 21:16 UTC, duane701 requested changes

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/subsystems/DooHickey.cpp
> +  ,mLogfile("/home/lvuser/test.txt", std::ios_base::out)
We can remove all of the log file stuff. The log file has served its purpose.

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/subsystems/DooHickey.cpp
> +    spinner.Config_kD(0, 0.0, 10);
Let's make P, I, D, F constants in this file that will be easier for use to find and change.

For example, near the beginning of this file

namespace
{
  constexpr double kF{0.3};
  constexpr double kP{0.1};
  // etc for I and D
}

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/subsystems/DooHickey.cpp
> +    mPreviousTime = std::chrono::system_clock::now();
Let's remove all the timing stuff as well.

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/subsystems/DooHickey.cpp
> +constexpr frc::DoubleSolenoid::Value kHickeyDisengage {frc::DoubleSolenoid::kReverse};
Put these two lines inside of `namespace {`.

2020-01-26 21:16 UTC, duane701 commented on src/main/include/subsystems/DooHickey.h
> +#include <fstream>
Remove `chrono` and `fstream`

2020-01-26 21:16 UTC, duane701 commented on src/main/include/subsystems/DooHickey.h
> +#include <frc/DoubleSolenoid.h>
Remove `WPILIb.h` and `Phoenix.h`. The includes here are close. Add any additional includes for pieces that are missing.

2020-01-26 21:16 UTC, duane701 commented on src/main/include/subsystems/DooHickey.h
> +  time_point mPreviousTime;
Remove mPreviousTime and mLogFile.

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/RobotContainer.cpp
> +  frc::SmartDashboard::PutData("Spin 6000 RPM", new Spin(mDooHickey, 0.9404));
Nice random numbers.

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/commands/SetHickeyPos.cpp
> +SetHickeyPos::SetHickeyPos(DooHickey* dooHickey, double position) : mDooHickey(dooHickey), mPosition(position) {
Let's use a reference to the subsystem.

```suggestion
SetHickeyPos::SetHickeyPos(DooHickey& dooHickey, double position) : mDooHickey(dooHickey), mPosition(position) {
```

2020-01-26 21:16 UTC, duane701 commented on src/main/include/commands/SetHickeyPos.h
> +  SetHickeyPos(DooHickey* dooHickey, double position);
Use a reference for `dooHickey`

```suggestion
  SetHickeyPos(DooHickey& dooHickey, double position);
```

2020-01-26 21:16 UTC, duane701 commented on src/main/include/commands/SetHickeyPos.h
> +  DooHickey* mDooHickey;
Reference

```suggestion
  DooHickey& mDooHickey;
```

2020-01-26 21:16 UTC, duane701 commented on src/main/include/commands/HickeyEngage.h
> +  DooHickey* mDooHickey;
`mDooHickey` is uninitialized and use a reference.

```suggestion
  DooHickey& mDooHickey;
```

2020-01-26 21:16 UTC, duane701 commented on src/main/include/commands/HickeyEngage.h
> +  HickeyEngage();
Need a subsystem

```suggestion
  HickeyEngage(DooHickey& dooHickey);
```

2020-01-26 21:16 UTC, duane701 commented on src/main/include/commands/HickeyDisengage.h
> +  HickeyDisengage();
Need a subsystem.

2020-01-26 21:16 UTC, duane701 commented on src/main/include/commands/HickeyDisengage.h
> +  DooHickey* mDooHickey;
mDooHickey is uninitialized and should be a reference.

```suggestion
  DooHickey& mDooHickey;
```

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/commands/HickeyEngage.cpp
> +HickeyEngage::HickeyEngage() {
Need a subsystem as a reference.

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/commands/HickeyEngage.cpp
> +  AddRequirements(mDooHickey);
When `mDooHickey` is a reference, change this too

```suggestion
  AddRequirements(&mDooHickey);
```

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/commands/HickeyDisengage.cpp
> +HickeyDisengage::HickeyDisengage() {
Need subsystem as reference.

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/subsystems/DooHickey.cpp
> +    gameData = frc::DriverStation::GetInstance().GetGameSpecificMessage();
I think this is going to be moved. I think the message only comes through when it's time to spin the wheel.

2020-01-26 21:16 UTC, duane701 commented on src/main/include/Robot.h
> +#include <subsystems/DooHickey.h>
Use `"` for our includes

```suggestion
#include "subsystems/DooHickey.h"
```

2020-01-26 21:16 UTC, duane701 commented on src/main/cpp/RobotContainer.cpp
> +  double radiusDW = 1.5;  //1.5" radius of DooHickey wheel (3" diameter)
Good info. We'll probably need this somewhere else.

2020-01-26 21:17 UTC, duane701 commented
FTP

2020-01-26 21:18 UTC, duane701 commented on src/main/cpp/subsystems/DooHickey.cpp
> +constexpr frc::DoubleSolenoid::Value kHickeyDisengage {frc::DoubleSolenoid::kReverse};
And then add PIDF with them

2020-01-28 04:50 UTC, duane701 commented
LGTM -- Rebase after Kenyon 

Or you can race. First one wins. Second one has to rebase -- again.

2020-01-30 00:50 UTC, jasonplatte commented
Replaced by #31

2020-01-30 00:50 UTC, closed without merging